import json

# Fungsi untuk menyimpan data ke dalam file JSON
def save_to_json(data):
    with open('database_makanan.json', 'w') as file:
        json.dump(data, file, indent=4)

# Fungsi untuk memasukkan data makanan, resep, dan harga ke dalam database
def insert_data(data, nama, deskripsi, kategori, bahan, instruksi, harga):
    # Membuat dictionary untuk menyimpan data baru
    new_data = {
        "Nama": nama,
        "Deskripsi": deskripsi,
        "Kategori": kategori,
        "Resep": {
            "Bahan": bahan,
            "Instruksi": instruksi
        },
        "Harga": harga
    }

    # Menambahkan data baru ke dalam list data
    data.append(new_data)

# Contoh input list makanan
database_makanan = []

# DATABASE HANIF
insert_data(database_makanan, "Salad Buah", "Campuran buah segar dengan saus yogurt", "appetizer", ["Apel", "Jeruk", "Anggur", "Pisang", "Saus yogurt"], "1. Potong buah-buahan. 2. Campurkan dengan saus yogurt.", [2000,3000,4000], 14000)
insert_data(database_makanan, "Risoles", "Suatu camilan dengan isian mayonais dan daging", "appetizer", ["Mayonais", "Wortel", "Daging", "Tepung Roti", "Kulit Risoles", "Telur"], "1. Campurkan semua bahan kulit, aduk rata. Saring agar tidak bergerindil. Adonan kulit tidak terlalu kental namun tidak terlalu cair juga. Diamkan selama 30 menit.Rebus telur dan dipotong-potong. Goreng sosis dan potong memanjang. 2. Campurkan mayonaise dengan kental manis, aduk rata. 3. Gunakan teflon anti lengket untuk membuat kulit. Ambil satu sendok sayur atau secukupnya. Ratakan hingga tipis dan matang mengelupas sendiri. Lakukan hingga adonan habis. 4. Ambil kulit dan isi dengan mayo, telur dan sosis. Lipat dan gulung risol. Rekatkan dengan bahan perekat. Lakukan hingga habis. 5. Campurkan terigu dengan air untuk pencelup. Celupkan risol ke pencelup dan balur dengan tepung roti. Simpan di dalam freezer selama 1 jam agar tepung roti merekat. 6. Goreng risol mayo hingga matang kecokelatan. Angkat dan sajikan.", 10000)
insert_data(database_makanan, "Dimsum Ayam Wortel", "Dimsum somay yang berisi ayam dan juga wortel", "appetizer", ["1/2 kg dada ayam cincang", "2 sdm tepung tapioka", "1 butir telur ayam", "1 bungkus kulit pangsit", "1 sdm bawang merah goreng", "3 siung bawang putih, haluskan", "5 sdm minyak wijen"], "1. Langkah pertama haluskan fillet daging ayam dan telur menggunakan blender. 2. Setelah halus, campurkan dengan kaldu bubuk, gula pasir, merica bubuk, saus tiram, minyak wijen, kecap asin, dan bawang putih goreng, aduk sampai adonan rata. 3. Tambahkan wortel yang sudah dicincang kasar dan potongan daun bawang, aduk rata. 4. Masukkan tepung tapioka dalam adonan, aduk hingga rata. 5. Ambil 1 lembar kulit dimsum, tambahkan isian dimsum, lalu bungkus dan lipat perlahan. 6. Taburkan parutan wortel di atas dimsum sebagai topping. Lalu kukus dimsum selama 25-30 menit. 7. Sajikan dan nikmati setelah matang.", 20000)
insert_data(database_makanan, "Garlic Bread", "Makanan pembuka roti dengan rasa bawang", "appetizer", ["4 lembar roti tawar", "1 sdm margarin", "2 siung bawang putih, haluskan", "peterseli secukupnya", "keju secukupnya"], "1. Campur bawang margarin, keju, dan peterseli. Aduk rata. Oleskan ke atas roti. 2. Oven dengan api bawah 180 derajat Celcius 10 menit hingga kering bagian atasnya.", 13000)
insert_data(database_makanan, "Rainbow Mille Crepe Cake", "Cake crepes dengan warna pelangi", "dessert", ["6 sdm butter, cairkan", "710 ml cups susu ", "6 butir telur", "280 g tepung", "7 sdm gula", "whipped cream secukupnya", "pewarna makanan secukupnya"], "1. Masukan tepung terigu, gula, dan telur, kemudian aduk rata.  2. Tambahkan butter yang telah dilelehkan dan campur dengan susu, aduk adonan hingga rata. 3. Pisahkan adonan ke dalam 6 mangkok yang berbeda. Beri pewarna makanan sesuai selera dan aduk rata. 4. Panaskan wajan dengan api sedang. Tuang adonan tipis-tipis ke wajan membentuk dadar tipis atau crepe. Lakukan hingga semua adonan habis. Angkat dan sisihkan. 5. Ambil satu lembar crepe dan olesi dengan whipped cream, kemudian tumpuk kembali dengan crepe dan olesi whipped cream. Lakukan hingga semua bahan habis.  6. Pada lapisan terakhir, tutup semua crepe dengan whipped cream hingga rata. 7. Sajikan dessert dalam keadaan dingin.", 35000)
insert_data(database_makanan, "Dessert Box Wafer", "Cake dengan topping yang disajikan dalam sebuah kotak plastik", "dessert", ["10 potong wafer rasa cokelat atau apa saja", "250 ml susu cair", "3 sdm kental manis", "2 sdm keju parut ", "1 sdm maizena, larutkan dengan air secukupnya", "1 sdt margarin"], "1. Hancurkan wafer hingga halus, sisihkan. 2. Untuk vla, panaskan susu cair dan kental manis. Aduk rata hingga larut. 3. Masukkan keju dan margarin, aduk rata. Tuang maizena yang sudah dilarutkan dengan air secukupnya, aduk hingga matang mengental. Angkat. 4. Siapkan wadah mika, tata wafer di dasar, tuang vla secukupnya, tabur wafer lagi, tutup lagi dengan vla. Beri sedikit tabura wafer halus di atasnya. 5. Simpan di dalam kulkas, nikmati dessert box selagi dingin", 32000)
insert_data(database_makanan, "Pretzel", "Pretzel merupakan kue khas Eropa yang punya rasa gurih manis", "dessert", ["450 g tepung terigu", "3 sdt ragi instan", "1 butir telur", "2 sdm gula", "1 sdt garam", "400 ml air hangat", "45 g soda kue", "2 l air"], "1. Campurkan terigu, gula pasir, ragi, serta garam. Tambahkan air matang sedikit demi sedikit sambil terus aduk adonannya sampai kalis. 2. Diamkan adonan pretzel hingga mengembang dalam wadah tertutup kain bersih selama 30-40 menit. 3. Kempiskan sedikit adonan yang sudah mengembang. Bagi adonan menjadi beberapa bagian berukuran masing-masing 50 gram. 4. Taburkan terigu di meja bersih supaya adonan tidak lengket. Gulung-gulungkan adonan hingga bentuknya memanjang. Buat adonan hingga membentuk kue pretzel yang bentuknya mirip hati namun seperti ada simpul pada bagian tengahnya. 5. Lakukan tahap 4 sampai adonan habis. 6. Buat bahan celupan. Rebus air sampai mendidih, matikan api. Setelah itu, tambahkan soda kue, aduk rata di air yang masih panas. 7. Tempatkan adonan kue pretzel di saringan bersih. Celupkan adonan di bahan celup sampai terendam selama 30 detik. Angkat, kemudian tiriskan. 8. Letakkan kue pretzel di loyang bersih. Oleskan margarin atau mentega di permukaannya, taburi dengan sedikit garam kasar. 9. Panggang pretzel di oven bersuhu 200 derajat celcius sampai matang, kurang lebih 15-20 menit. 10. Keluarkan pretzel dari oven. Sajikan.", 45000)
insert_data(database_makanan, "Rendang daging", "Daging dengan bumbu rendang", "main course", ["1 kg daging sapi bagian paha", "2500 ml santan", "3 batang serai digeprek", "8 lembar daun jeruk", "5 lembar daun salam", "250 gr cabai keriting merah dan rawit", "250 gr bawang merah", "8 siung bawang putih", "1 sdt jintan", "5 butir cengkeh", "3 butir kemiri","Seruas jahe, kunyit, lengkuas", "Garam dan gula secukupnya"], "1. Potong-potong daging kira-kira 1 kg jadi 20 potong. 2. Masukkan santan ke dalam wajan, tambahkan serai, daun jeruk, daun salam dan bumbu halus. Masak di atas api kecil sambil terus diaduk perlahan. Cara mengaduknya seperti orang menimba. Santan diaduk di bagian permukaannya, diambil sedikit demi sedikit dengan sendok sayur. Timba-timba santan hingga mendidih sekitar 15 menit .3. Masukkan daging, aduk-aduk hingga mendidih, kecilkan api. Beri garam dan gula secukupnya. Masak sampai santan mengental, aduk supaya tidak gosong. 4. Teruskan memasak dengan api kecil sampai rendang mengering dan berminyak.", 40000)
insert_data(database_makanan, "Nasi Goreng", "Nasi yang digoreng dengan bumbu", "main course", ["Nasi", "Telur", "Bawang", "Kecap"], "1. Goreng nasi. 2. Masukkan telur dan bumbu-bumbu lain.", 25000)
insert_data(database_makanan, "Pancake", "Pancake lezat dengan sirup maple", "dessert", ["Tepung", "Susu", "Telur", "Gula", "Sirup maple"], "1. Campurkan bahan-bahan. 2. Goreng pancake hingga matang.", 20000)
insert_data(database_makanan, "Nasi Goreng", "Nasi yang digoreng dengan bumbu", "main course", ["Nasi", "Telur", "Bawang", "Kecap"], "1. Goreng nasi. 2. Masukkan telur dan bumbu-bumbu lain.", 25000)
insert_data(database_makanan, "Salad Sayuran", "Campurkan berbagai sayuran segar", "diet food", ["Daun selada", "Tomat", "Timun", "Paprika", "Dressing rendah kalori"], "1. Cuci sayuran. 2. Iris dan campurkan dengan dressing rendah kalori.", 18000)

# DATABASE AKMAL 
insert_data(database_makanan, "Tongkol Suwir Pedas", "Olahan Tongkol dengan Sambal", "main course", ["2 lembar daun jeruk ", "1 buah jeruk nipis", "Garam", "Gula", "Kaldu bubuk", "Minyak goreng","3 siung bawang putih","5 buah cabai merah besar","4 siung bawang merah","10 buah cabe rawit merah"], "1. Rebus ikan tongkol sampai matang, angkat dan suwir 2. Haluskan seluruh bumbu halus dengan blender. 3.Tumis bumbu halus sampai harum" "4. Tambahkan daun jeruk, perasan jeruk nipis, air, garam, dan gula 5.Masukkan ikan yang telah disuwir, aduk hingga merata 5.Diamkan sejenak hingga bumbu terserap sempurna. 6. Angkat lalu sajikan di piring.", 15000)

insert_data(database_makanan, "Capcay Goreng", "Olahan sayuran dengan bumbu", "main course", ["Kol", "Sawi", "Wortel", "Brokoli", "Bakso", "Pakcoy", "Jamur","saos","kecap asin","saus tiram"], "1. Panaskan wajan kemudian tumis bawang putih dan cabai merah hingga harum. 2. Tuang telur dan orak arikkan telur. 3.Kemudian tambahkan buncis dan jamur. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 10000)

insert_data(database_makanan, "Gado Gado", "Olahan sayuran, tempe dan tahu dengan bumbu kacang", "main course", ["mentimun", "kol", "tahu", "tempe", "labu siam", "kacang panjang", "tomat","kerupuk","emping","Buncis", "kentang","buncis","taoge","telur"], "1. Aduk rata tempe dan tahu bersama bumbu perendam. Sisihkan. 2. Panaskan minyak, goreng tahu dan tempe hingga garing dan matang. Angkat dan tiriskan. 3.Bumbu kacang: Panaskan 3 sdm minyak, tumis bumbu halus dan daun jeruk hingga harum. Masukkan kacang tanah dan Bango Kecap Manis, aduk rata. Tambahkan sisa semua bahan, aduk. Masak hingga matang. Angkat. Biarkan hingga tidak panas 4.Tata kentang, tahu, tempe, daun selada, ketimun, taoge, dan kol di atas piring saji. Tuang bumbu kacang dan taburi bawang merah goreng. Sajikan dengan pelengkap 5.Angkat dan sajikan" ,  12000)

insert_data(database_makanan, "Martabak", "Olahan sayuran dan daging yang dibalut dengan kulit lumpia", "appetizer", ["kulit lumpia", "Bawang Putih", "daging ayam", "bawang putih", "1/4 sendok teh merica bubuk", "telur"], "1. campurkan 5 gram daun bawang, diiris halus 2 butir telur bebek, dikocok lepas 1/2 buah bawang bombay cincang halus 1/2 sendok teh garam 1/4 sendok teh merica bubuk 50 gram bahan tumisan daging. 2. Tuang telur dan orak arikkan telur. 3.Kemudian tambahkan buncis dan jamur. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 10000)

insert_data(database_makanan, "Kangkung Balacan", "Olahan kangkung dengan bumbu balacan", "diet food", ["Kangkung", "Tomat", "2 Cabai Merah", "1 sdt terasi", "sedikit garam", "2 siung bawang putih", "gula secukupnya","2 buah cabai rawit","minyak goreng"], "1. Rebus kangkung, angkat dan tiriskan. 2. Tumis bumbu yang sudah ditumbuk sampai berbau harum dan matang, masukkan tomat sampai layu. 3. Hidangkan rebusan kangkung dengan menyiram bumbu di atasnya. Siap sajikan. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 7000)

insert_data(database_makanan, "Telur Sambal", "Olahan Telur dengan sambal pedas", "main course", ["4 buah telur ayam, rebus matang lalu goreng hingga berkulit", "2 siung bawang putih", "8 butir bawang merah", "2 buah cabai merah besar", "10 buah cabai rawit","1 lembar daun jeruk, buang tulangnya", " 1 buah tomat iris", "1/2 sdt terasi matang", "gula, garam, kaldu bubuk secukupnya"], "1. Tumis bahan sambal bersama terasi dan daun jeruk hingga harum dan matang, beri air secukupnya 2. Masukkan telur dan irisan tomat, bumbui dengan gula, garam dan kaldu bubuk, koreksi rasanya, masak hingga kuah asat 3.Taburi daun bawang, siap disajikan", 10000)

insert_data(database_makanan, "Sup Ayam Kentang", "Olahan Ayam dengan Sup Kentang yang fresh", "appetizer", ["200 gram kentang", "2 siung bawang putih", "100 gram wortel", "250 gram daging ayam", "1 tangkai seledri", "1 batang daun bawang"], "1. Tumis Bumbu yang telah di haluskan hingga tercium wangi nya 2. Tambahkan garam dan merica secukupnya 3.Tambahkan 1 Liter air 4. Jika sudah mendidih masukkan ayam dan sayuran 5. Aduk sampai merata 6. Tunggu sampai matang 7. Tiriskan dan ambil kuah secukupnya 8. Sajikan selagi masih hangat", 25500)

insert_data(database_makanan, "Tinutuan", "Olahan beras yang menjadi bubur dimasak dengan aneka umbi dan sayur", "appetizer", ["200 gram labu kuning, kukus", "100 gram labu kuning", "100 gram jagung manis", "150 gram beras", "2 liter air","1 sdm garam", "2 ikat daun kangkung", "2 ikat daun bayam", "3 tangkai daun kemangi", "100 gram ikan cakalang", "3 sdm sambal roa", "3 buah lemon"], "1. Kukus serta haluskan labu kuning 2. Potong kotak labu kuning 3. rebus jagung manis serta pipilkan 4. siangi 2 ikat daun kangkung serta daun bayam 5. Ambil daun kemangi dari tangkai nya 6. Potong-potong ikan cakalang 7. Dalam satu panci besar, rebus beras, air, labu kuning yang sudah dikukus, dan beri garam. Aduk sampai beras setengah matang 8. Masukkan jagung, ubi merah, labu kuning. Aduk dan masak sampai matang 9.Saat bubur sudah matang, masukkan kangkung, bayam, dan daun kemangi 10. Sajikan dengan sambal roa dan suwiran ikan cakalang", 15000)

insert_data(database_makanan, "Salad Buah Mayonaise", "Olahan Salah buah dengan saos mayonaise", "appetizer", ["1 Buah pir", "1 Buah Sunkist", "1 Buah jeruk medan", "0.5 Buah bengkoang", "150 gram Anggur merah", "100 gram Strawberry", "6 sdm Mayonaise", "4 sdm Susu Kental Manis", "Keju parut secukupnya"], "1. Cuci Bersih buah 2. Potong buah sesuai selera potongan 3. Campurkan semua buah ke dalam satu wadah 4. Beri mayonaise buah yang suah di campurkan 5. Berikan taburan keju parut dan aduk kembali sampai rata 6. Sajikan dengan porsi yang di inginkan", 17000)

insert_data(database_makanan, "Pancake Mangga", "Buah mangga yang di lapisi dengan kulit pancake", "dessert", ["125 gr tepung terigu", "1 butir telur ayam", "1/4 sdt garam", "275 ml susu cair", "Buah Mangga", "Whip Cream"], "1. kocok telur ayam terlebih dahulu 2. Campurkan tepung terigu, garam dan telur jadi satu 3.Tambahkan susu cair secara perlahan sambil diaduk-aduk 4. Saring adonan 5. Dadar di tempat penggoreng sampai adonan habis 6. Isi kulit pancake dengan whipping cream dan mangga, lipat seperti amplop 7. Simpan pancake di kulkas. Pancake mangga enak dimakan dalam kondisi dingin", 1900)

insert_data(database_makanan, "Taco Ikan", "Taco Ikan dengan selada dan kubis herbal", "diet food", ["Ikan Tuna","kulit lumpia","kubis","selada","Tarragon","jeruk nipis", "garam", "½ cangkir krim asam", "1 sdt jintan tanah1 jalapeno","2 sdm air jeruk nipis", "Perasan 1 buah jeruk nipis"], "1. Bersihkan Tuna dan Potong sesuai selera, 2. Campurkan bahan selada dan kubis serta beri garam 3. Tunggu 10 menit 4. Campurkan bahan untuk krim dan beri bumbu dengan garam 5. Goreng Ikan tuna dengan bumbu selada serta sudah di bungkus dengan kulit lumpia 6. Setelah itu sajikan di piring", 45000)

insert_data(database_makanan, "Steak Tempe", "Steak versi diet food dengan sayur dan kacang", "diet food", ["1/2 papan tempe", "2 sdm tepung gluten free", "1/2 sdt lada putih", "garam secukupnya", "minyak kelapa", "air secukupnya"], "1. Kukus tempe sampai matang. Kemudian haluskan. 2. Campur tempe dengan tepung, lada putih, dan garam. 3. Bentuk sesuai selera, masak dengan api kecil hingga matang. Angkat dan sisihkan. 4. Saus: tumis bawang putih sampai harum. Masukkan bawang bombay, aduk sampai layu. 5. Masukkan semua bahan lain kecuali garam. Masak sampai mendidih. 6. Matikan api, beri garam lalu aduk rata. 7. Tuang saus ke steak tempe.", 13000)

insert_data(database_makanan, "Sup kacang merah", "Sup dengan versi diet serta tambahan kacang merah yang lezat", "diet food", ['kentang', '2 butir telur', 'timun', 'tomat', 'selada', 'wortel', '150 ml air', '2 sdm fiber krim', '1 sdt garam', '1 sdm air lemon'], '1. Didihkan air, masukkan fiber creme lalu aduk rata. 2. Masukkan larutan maizena, aduk sampai mengental. 3. Beri himsalt dan air lemon, aduk rata. 4. Sajikan sayur dan telur dengan saus yang sudah jadi.', 6000)

insert_data(database_makanan, "Dimsum gulung sawi", "Dimsum dengan versi diet food di bungkus dengan sawi", 'diet food', ['500 gr paha ayam fillet', '100 gr udang', '2 putih telur', '2 siung bawang putih yang sudah dihaluskan', '4 sdm saus tiram non MSG', '1/2 sdt garam', '1 sdt kecap asin organik', '1 ujung sendok lada', 'sawi'], '1. Haluskan semua bahan kecuali sawi. 2. Gulung isian dengan sawi yang sudah direbus di air mendidih sebentar. 3. Kukus sampai matang.', 7000)

insert_data(database_makanan, "Mi Ayam Shirataki", "Mi ayam dengan versi diet food", "diet food", ['50 gr ayam giling', '1 sdm bawang putih halus', 'Garam', 'Lada', 'Kulit ayam', 'Lemak ayam', 'Mie shirataki sceukupnya', '2 sdt kecap asin', '1 sdm minyak ayam', '1/2 sdt merica bubuk'], '1. Masak semua bahan topping di teflon hingga kering dan keluar minyak nya. 2. blender hingga halus bahan yang ada di teflon. 3. Masak minyak ayam kulit dan lemak dimasak tanpa minyak hingga keluar minyaknya. 3. Rebus mi shirataki 4. angkat dan tiriskan 5. Beri kecap asin, minyak ayam, dan lada bubuk di mangkuk lalu aduk hingga rata. 6. Setelah di aduk sampai merata sajikan dengan tambahan topping', 12500)

insert_data(database_makanan, "Green Pasta", "Pasta yang cocok untuk yang sedang diet", "diet food", ['Fettucine secukupnya', 'Brokoli', '1 buah tomat kecil', '1/4 paprika hijau', '3 siung bawang putih yang cincang halus', 'Lada hitam', '1 sdm minyak wijen', 'Garam himalaya', '2 buah telur ayam ambil bagian putih nya saja'], '1. Rebus fettuccine dan brokoli. Jika sudah matang tiriskan. Air bekas rebusan pasta disisakan sedikit.2. Panaskan penggorengan, masukkan minyak jagung, tumis bawang putih sebentar saja. 3. Masukkan tomat hijau dan paprika hijau. Tumis sebentar, masukkan air bekas rebusan pasta sedikit. 4. Masukkan fettuccine, brokoli, dan telur orak arik. 5. Tambahkan minyak wijen, garam himalaya, dan lada hitam sesuai selera. 6. Aduk sebentar kira-kira 3-5 menit', 18000)

#DATABASE RAFLI
insert_data(database_makanan, "Sup Sayur", "Sup dengan aneka sayur ", "appetizer", ["1 buah Wortel", "¼ bagian Kol", "¼ bagian Bunga kol", "1 batang Daun bawang", "1 batang Seledri", "1 buah Kentang", "2 butir Bawang putih", "2 butir Bawang merah", "1 sdt lada bubuk", "1 sdm Kaldu bubuk", "1 sdm Minyak goreng", "1 bungkus Makaroni", "Garam secukupnya", "Air secukupnya"], "1. Potong wortel, kol, bunga kol, daun bawang, seledri dan kentang. 2. Haluskan bumbu bawang putih, bawang merah, lada, dan garam. 3. Tumis bumbu hingga wangi, lalu tambahkan air. 4. Masukkan sayur-sayuran dan makaroni, tambahkan kaldu bubuk. 5. Rebus hingga masak, dan siap disajikan", 7000)
insert_data(database_makanan, "Onion Rings", "Bawang bombay bentuk ring goreng tepung", "appetizer", ["1 buah Bawang Bombay", "20 gram Tepung Bumbu Serbaguna", "20 gram Tepung panir", "Air secukupnya", "Minyak Goreng"], "1. Cuci bawang bombay lalu iris membentuk lingkaran. 2. Buat adonan basah dengan mencampur air dan tepung bumbu. 3. Masukkan irisan bawang bombay ke adonan basah lalu lumuri dengan tepung panir. 4. Goreng hingga kuning kecoklatan, tiriskan, lalu siap disajikan.", 13500)
insert_data(database_makanan, "Udang Alpukat", "Udang panggang diatas krim alpukat dan mentimun", "appetizer", ["250 gram Udang", "1 butir Bawang putih", "½ sdt ketumbar", " ½ sdt Cabai bubuk", "½ sdt Garam", "2 sdm Minyak zaitun", "1/4 sdt lada hitam", "1 buah Alpukat", "Jeruk nipis secukupnya", "½ buah Mentimun"], "1. Masukkan udang dalam mangkuk, dan tambahkan bawang putih cincang,ketumbar, cabai bubuk, garam, lada, dan minyak zaitun. 2. Tumis udang hingga matang. 3. Masukkan alpukat, garam, air jeruk nipis, campur hingga merata. 4. Potong tipis mentimun. 5. Tata irisan mentimun, letakkan krim alpukat diatasnya, dan letakkan tumisan udang diatas krim alpukat. 6. Makanan siap disajikan", 40000)
insert_data(database_makanan, "Soto Lamongan", "Soto khas Lamongan dengan kuah kuning dan taburan koya yang gurih", "main course", ["100 gram Daging Ayam", "1 siung Serai", "2 lembar Daun Jeruk", "2 lembar Daun Salam", "1 cm Lengkuas", "2 sdt Garam", "1 batang Daun Bawang", "Air secukupnya", "Bumbu halus (1 butir Bawang merah, 2 butir Bawang putih, 1 butir Kemiri, 2 cm Kunyit, ½ sdt Merica)", "Koya", "200 gram Soun", "1 buah Tomat", "2 lembar Kol", "1 butir Telur", "Seledri secukupnya", "Jeruk Nipis secukupnya"], "1. Haluskan bumbu halus. 2. Iris tomat, seledri, kol, dan daun bawang. 3. Rebus daging ayam hingga matang dan berkaldu. 4. Tumis bumbu halus hingga wangi lalu tambahkan garam, serai, lengkuas, daun jeruk, daun salam, dan kaldu ayam. 5. Goreng ayam hingga matang, lalu suwir-suwir ayam. 6. Tata soun, tomat, kol, telur rebus, dan suwiran ayam dalam mangkuk, lalu tambahkan kuah soto. 7. Taburkan koya, seledri dan daun bawang sesuai selera", 12000)
insert_data(database_makanan, "Steak Ayam", "Steak ayam dengan saus pedas manis", "main course", ["1 potong Dada ayam", "½ sdt Merica bubuk", "1 butir bawang putih parut", "1 sdt garam", "1 sdm Mentega", "2 sdm Minyak sayur", "1 buah Bawang bombay cincang halus", "3 buah Cabai rawit", "1 sdm Tepung terigu", "250 mL Kaldu ayam", "1 sdm Kecap manis", "1 sdm Saus tiram", "Kentang goreng", "Salad sayur"], "1. Cuci bersih daging dada ayam. Kerat-kerat permukaannya di beberapa tempat. 2. Lumuri daging ayam dengan bawang putih, merica dan garam hingga rata. Diamkan beberapa saat. 3. Panaskan mentega dalam wajan hingga leleh. Kecilkan api, masukkan daging dada ayam. 4. Masak hingga kedua sisinya kering dan matang, angkat dan sisihkan. 5. Tumis bawang bombay dan bawang putih hingga layu dan harum. 6. Taburkan tepung terigu lalu aduk hingga tercampur rata. 7. Tuangi kaldu sambil aduk hingga agak kental. 8. Tambahkan bahan-bahan lainnya dan masak hingga mendidih. 9. Masukkan daging dada ayam, masak sebentar hingga mendidih lalu angkat. 10. Sajikan dengan salad sayur dan kentang goreng.", 24000)
insert_data(database_makanan, "Bubur Candil", "Bubur dengan bulatan kenyal yang legit", "dessert", ["50 gram Tepung Ketan", "1 sdm Tepung beras", "2 sdm Tepung tapioka", "Air secukupnya", "50 gram Gula merah", "2 lembar Daun pandan", "Garam secukupnya", "75 mL Santan"], "1. Didihkan air, gula merah, garam, dan daun pandan. 2. Campur tepung ketan, tepung beras, air secukupnya, dan garam, kemudian buat bulatan kecil. 3. Masukkan bulatan candil kedalam rebusan pada langkah pertama. 4. Tuang tepung tapioka dan sedikit air. 5. Didihkan santan dengan daun pandan dan garam. 6. Sajikan bubur candil dengan siraman santan", 8000)
insert_data(database_makanan, "Pie Buah", "Pie dengan topping buah segar", "dessert", ["250 gram Tepung Terigu", "1 sdm Gula halus", "170 gram Mentega", "1 butir Kuning telur", "Susu cair", "1 sdt Gula pasir", "40 gram Tepung Meizena", "½ sdt Vanilla bubuk", "Air 100 mL", "Aneka buah"], "1. Campur beberapa bahan ini sekaligus yakni terigu, gula halus, mentega. Setelah itu aduk menggunakan sendok kayu atau pisau pastry sampai berbulir kemudian tambahkan kuning telur, dan aduk rata. 2. Bentuk adonan menjadi bulat-bulat, selanjutnya taruh cetakan pie dalam bentuk molding yang sudah dioles butter. Jangan lupa pakai garpu untuk menusuk bagian dasar pie supaya tidak menggelembung. 3. Sekarang giliran memanggang. Perhatikan suhu 165/170’c api atas bawah dan mulai panggang pie hingga matang. Akan memakan waktu sekitar 25 menit atau sesuaikan oven masing-masing. 4. Ambil tepung maizena kemudian cairkan dengan susu cair (seperlunya saja), campur 5 butir kuning telur, aduk rata. 5. Kini rebus susu cair sisa ditambah gula hingga mendidih. Masukkan campuran maizena dan kuning telur, aduk cepat, terus biarkan mendidih sekali lagi. Angkat. dan sisihkan. 6. Isi pie dengan fla, tambahan hiasan potongan buah, siram 1 sdt agar-agar bening. Dan siap sajikan.", 16500)
insert_data(database_makanan, "Roti Gandum Telur Alpukat", "Roti gandum panggang dengan telur dan alpukat", "diet food", ["2 lembar roti gandum", "1 buah Telur", "1 buah Alpukat", "2 sdm Mentega", "Garam secukupnya"], "1. Panggang roti gandum dengan mentega hingga matang lalu sisihkan. 2. Panggang telur dengan mentega dan beri sedikit garam hingga matang lalu sisihkan. 3. Haluskan buah alpukat. 4. Oleskan alpukat di atas kedua roti. 5. Letakkan telur disalah satu roti lalu tutup dengan roti satunya", 10000)
insert_data(database_makanan, "Smoothie Hijau Buah dan Sayur", "Smoothie hijau dengan campuran buah dan sayur untuk pelengkap menu diet", "diet food", ["1 buah Mentimun", "½ buah Nanas", "1 batang Seledri", "200 mL Air", "50 gram Yogurt"], "1. Potong timun, nanas, dan seledri. 2. Masukkan bahan ke dalam blender. 3. Blender hingga halus, kemudian smoothie hijau siap disajikan", 16000)
insert_data(database_makanan, "Granola", "Campuran gandum utuh, kacang-kacangan dan buah kering yang sehat", "diet food", ["1 cup Rolled oat", "2 sdm Madu", "1 sdm Minyak zaitun", "2 sdm Kacang-kacangan","2 sdm Buah kering (kurma, berries, kismis, dll.)", "Susu atau yogurt secukupnya", "Gula aren"], "1. Sangrai rolled oat dan kacang-kacangan hingga kecoklatan. 2. Masukkan bahan untuk saus, antara lain minyak zaitun,gula aren, madu, dan buah kering. 3. Campur dengan rata siap di sajikan dengan susu atau yogurt.", 30000)

#DATABASE JULIE
insert_data(database_makanan, "Tumis Jamur", "Tumisan jamur rendah kalori","diet food", ["1 bungkus jamur tiram", "1 siung bawang putih", "garam, gula", "kecap"], "1. Suir jamur tiram sesuai selera. 2. Iris tipis bawang putih. 3. Panaskan wajan dengan sedikit minyak. 4. Masukkan bawang putih lalu tumis sampai harum. 4. Masukkan jamur lalu tumis sampai jamur terlihat layu. 5. Masukkan per bumbuan seperti gula dan garam sesuai selera, dan tambahkan kecap sesuai selera. 6. Aduk sampai rata lalu tambahkan sedikit air. 7. Aduk sebentar lalu tumis siap dihidangkan.", 5000)
insert_data(database_makanan, "Pepes Ayam", "Olahan ayam rendah kalori", "diet food", ["1/4 kg dada ayam", "3 siung bawang putih", "4 buah bawah merah", "4 cabai merah", "bumbu dapur; gula dan garam", "daun pisang untuk pembungkus"], "1. Haluskan bawang merah, bawang putih, dan cabai merah. 2. Potong dadu dada ayam ukuran sedang. 3. Siapkan mangkok, masukkan ayam dan bumbu yang sudah dihaluskan. 4. Tambahkan bumbu dapur, 1 sendok teh garam dan setengah sendok teh gula. 5. Aduk secara merata. 6. Siapkan daun pisang dan bungkus ayam yang telah dibumbui tadi menggunakan daun pisang. 7. Lalu, setelah dibungkus dengan rapat, kukus bungkusan tersebut selama 20 menit. 8. Pepes siap dihidangkan.", 20000)
insert_data(database_makanan, "Shrimp Salad", "Olahan sayur dengan udang", "diet food", ["1/4 kg udang", "kubis", "wortel", "jagung", "selada", "saus wijen instan"], "1. Bersihkan udang dengan membuang bagain kepala, kaki, dan kulit. 2. Rebus udang dan jagung sampai matang. 3. Potong potong sayuran sesuai selera (untuk wortel sebaiknya dipotong secara tipis tipis seperi batang korek api yang dibagi menjadi 2). 4. Cuci semua sayuran yang telah dipotong dan keringkan. 5. Siapkan mangkok, tata semua sayuran yang telah kering dan jagungnya, tidak lupa udang juga di tata sesuai selera. 6. Siram dengan 3 sendok saus wijen instan. 7. Shrimp Salad siap dihidangkan", 25000)
insert_data(database_makanan, "Mie goreng shirataki", "Mie goreng dengan bahan yang lebih sehat dan rendah kalori", "diet food", ["1 paket mie shirataki", "2 siung bawang putih (cincang halus)", "1 buah wortel (potong tipis)", "1 batang daun bawang (iris tipis)", "100 gram daging ayam (potong dadu kecil)", "2 sendok makan saus tiram", "1 sendok makan kecap manis", "1 sendok teh kecap asin", "1 sendok teh gula pasir", "1/2 sendok teh merica bubuk"], "1. Rendam mie shirataki dalam air panas selama 2-3 menit untuk menghilangkan bau khasnya. 2. Kemudian, tiriskan dan sisihkan. 3. Selanjutnya, panaskan minyak goreng dalam wajan yang sudah dipanaskan. 4. Tumis bawang putih hingga harum dan agak kecokelatan. 5. Masukkan potongan daging ayam dan aduk hingga berubah warna menjadi putih. 6. Tambahkan wortel dan aduk rata. 7. Masak sebentar hingga wortel sedikit lunak. 8. Kemudian, masukkan mie shirataki yang sudah direndam dan aduk hingga semua bahan tercampur secara merata. 9. Setelah itu, tuangkan saus tiram, kecap manis, dan kecap asin ke dalam wajan. 10. Tambahkan gula pasir dan merica bubuk. Aduk semua bahan secara merata, pastikan mie dan bumbu tercampur dengan baik. 11. Masak mie goreng shirataki dalam wajan dengan api sedang selama 3-4 menit atau hingga mie matang dan semua bumbu terserap. Jangan lupa untuk terus diaduk agar bumbu terdistribusi dengan baik. 12. Lalu, tambahkan irisan daun bawang dan aduk sebentar hingga tercampur rata. Angkat mie goreng shirataki dari wajan dan sajikan selagi hangat.", 35000)
insert_data(database_makanan, "Pindang Telur", "Telur rebus yang dimasak dengan proses pindang", "diet food", ["2 butir telur ayam", "2 lembar daun salam", "500 ml air untuk merebus", "Irisan 1 sdm bawang merah", "Irisan 1 sdm bawang putih", "1 sdm air asam", "1 ruas lengkuas", "1 sdt garam"], "1. Rebus telur dengan air dan semua bumbu dengan api sedang hingga telur matang dan air menyusut, 2. Angkat telur lalu ketuk-ketuk kulit telur hingga retak, 3. Masukkan kembali ke air rebusan lalu masak hingga air menyusut. 4. Lalu angkat, kupas telur dan hidangkan.", 10000)
insert_data(database_makanan, "Tumis Tahu Tauge", "Tumisan berisi tahu dan tauge rendah kalori", "diet food", ["5 tahu putih ", "1 genggam tauge","2 siung bawang putih", "1 sachet saos tiram", "bumbu dapur (gula dan garam)"], "1. Potong tahu putih menjadi kotak dadu sesuai selera. 2. Cincang bawang putih. 3. Panaskan wajan dengan menggunakan 1 sendok air lalu masukkan bawang putih yang sudah di cincang. 4. Jika sudah wangi masukkan tahu lalu tumis sebentar, lalu masukkan tauge dan aduk sampai tauge lemas. 5. Masukkan saos tiram dan beri tamabahan bumbu dapur sesuai selera. 6. Tumis tahu tauge siap dihidangkan.", 10000)
insert_data(database_makanan, "Mashed Potato", "Kentang tumbuk pengganti nasi rendah kalori", "diet food", ["2 buah kentang", "1 sendok makan mentega", "garam"], "1. Kukus/ rebus kentang sampai menjadi empuk. 2. Tumbuk halus kentang. 3. Masukkan 1 sendok makan mentega. 4. Aduk sampai rata dan tambahkan garam secukupnya atau sesuai selera. 5. Mashed potato siap dihidangkan.", 5000)
insert_data(database_makanan, "Klepon", "Jajanan tradisional untuk makanan penutup", "dessert", ["1/2 kg Tepung ketan", "gula merah", "pewarna makanan warna hijau", "kelapa parut"], "1. Campurkan tepung ketan dengan pewarna makanan hingga terbentuk adonan yang lembut dan tidak lengket. 2. Setelah itu, bentuk adonan menjadi bola-bola kecil dengan diameter sekitar 2-3 cm. 3. Selanjutnya, siapkan gula merah yang telah dipotong-potong menjadi bagian kecil. Ambil satu bola adonan ketan, pipihkan dan letakkan sejumput gula merah di tengahnya. 4. Rapatkan kembali adonan ketan hingga gula merah terbungkus sempurna. 5.Selanjutnya didihkan air dalam panci dan masukkan bola-bola klepon ke dalam air mendidih. Rebus klepon hingga bola-bola tersebut mengapung di permukaan air, yang menandakan bahwa klepon telah matang. 6. Angkat klepon dari air mendidih dan tiriskan. 7. Langkah terakhir, gulingkan klepon yang masih hangat ke dalam kelapa parut yang telah dipersiapkan. 8. Klepon siap disajikan dan dapat dinikmati dalam keadaan hangat atau dingin.", 10000)
insert_data(database_makanan, "Dadar Gulung", "Jajanan tradisional berisi parutan kelapa yang dicampur dengan gula merah", "dessert", ["tepung terigu", "telur", "gula", "garam", "santan", "air"], " 1.Campurkan tepung terigu, telur, gula, dan garam, lalu aduk rata. 2.Tambahkan santan sedikit demi sedikit sambil terus diaduk hingga membentuk adonan yang kental. 3. Selanjutnya, panaskan wajan anti lengket dan oleskan sedikit minyak. 4. Tuangkan adonan dadar ke dalam wajan dan ratakan dengan spatula. Biarkan dadar matang di satu sisi, kemudian balik dan biarkan matang sempurna. 5. Setelah dadar matang, pindahkan ke piring dan biarkan sedikit dingin. 6. Kemudian, beri isian sesuai selera, seperti gula merah parut, keju, atau selai, dan gulung dadar dengan rapi. 7.  Dadar gulung siap disajikan.",15000)
insert_data(database_makanan, "Dessert Box", "Makanan penutup yang disajikan dalam satu kotak", "dessert", ["satu bungkus oreo", "1 bungkus whipcrem siap kocok"], "1. Pisahkan cream dengan biskuit oreo. 2. Tumbuk kasar biskuit oreo yang telah dipisahkan dari creamnya. 3. Siapkan wadah untuk menuang whip cream kocok dan krim oreo. 4. Aduk wip cream dan krim oreo sampai kental dan padat. 5. Siapkan wadah lalu tata oreo dan krim layer per layer. 6. Dessert box siap dihidangkan atau masukkan kulkas terlebih dahulu agar lebih nikmat", 20000)
insert_data(database_makanan, "Bolu Pisang", "Makanan penutup dengan bahan dasar pisang", "dessert", ["2 buah pisang matang, haluskan","1 butir telur","100 gram tepung terigu","50 gram gula pasir","1 sendok makan margarin, lelehkan","1/2 sendok teh baking powder", "1/2 sendok teh vanili bubuk","Secubit garam"], "1. campurkan pisang halus dengan telur dan gula pasir dalam sebuah mangkuk. 2. Aduk rata hingga gula larut dan bahan tercampur dengan baik. 3. Selanjutnya, tambahkan tepung terigu, baking powder, minyak sayur, dan garam ke dalam campuran pisang. 4. Aduk kembali hingga semua bahan tercampur secara merata, tetapi jangan terlalu lama mengaduknya agar adonan tidak terlalu padat. 5. Selanjutnya, siapkan loyang atau wadah yang bisa digunakan untuk kukusan. 6. Olesi permukaan loyang dengan sedikit minyak agar bolu tidak lengket. 7. Tuangkan adonan bolu pisang ke dalam loyang yang telah disiapkan. Pastikan adonan tidak terlalu penuh karena bolu akan mengembang saat dikukus. 8. Panaskan panci kukusan dengan air di bawahnya. Setelah air mendidih, letakkan loyang yang berisi adonan bolu pisang ke dalam panci kukusan. 9. Tutup panci dengan rapat dan kukus selama sekitar 30-40 menit atau hingga bolu matang. 10. Gunakan tusuk gigi untuk memeriksa kekematangan bolu, jika tusuk gigi keluar bersih tanpa adonan yang menempel, maka bolu sudah matang.", 12000)

#DATABASE ALVAN
insert_data(database_makanan,"Tom Yum Seafood","Olahan Tom Yum Seafood","main course", ["1 daun salam", "2 daun jeruk", "1 serai geprek", "1 ruas jahe geprek", "1 ruas rengkuas geprek", "1 sdm air jeruk nipis"], "1. Tumis bumbu halus, masukkan bumbu pelengkap 2. Tuang air secukupnya, masukkan cumu, tunggu hingga empuk.3.Masukkan bahan lainnya, beri garam, kaldu, dan lada bubuk.",15000)
insert_data(database_makanan,"Gulai Ayam", "Olahan Gulai Ayam", "main course",["1 ekor ayam ", "1 buah jeruk nipis ", "1 batang serai geprek", "2 lembar daun salam", "2 lembar daun jeruk", "200 ml santan encer", "200 ml santan kental","air matang secukupnya"],"1.Cuci bersih daging ayam dan lumuri dengan jeruk nipis 2.Tumis bumbu halus sampai wangi, masukkan daun dalam,daun jeruk,dan sereh, aduk sampai bumbu matang,masukkan ayam , aduk rata,masak samapi berubah warna, tambahkan garam dan kaldu.3.Masukkan santan encer dan air, masak dengan api sedang sampai daging ayam empuk 4.Setelah kuah menyusut dan daging ayam empuk, masukkan santan kental, masak sambal terus diaduk sampai santan mendidih  dan bumbu meresap.",10000)
insert_data(database_makanan,"Nasi liwet teri","MainCourse","main course",["350 gram beras","4 batang serai geprek","3 cm lengkuas daun salam","3 lembar daun salam", " 4 lembar daun jeruk","150gram teri goreng kering","3/2 sdt garam","1 sdt kaldu bubuk non msg","minyak goreng"],"1. Tumis bawang merah dan bawang putih, masukkan cabai hingga layu. Masukkan daun salam, sereh, dan daun jeruk. Masak hingga wangi. Angkat dan sisihkan 2.Masukkan beras ke rice cooker, tuang air, masukkan tumisan bumbu iris, garam, dan kaldu bubuk. Aduk rata. Masak hingga matang.3. Masukkan teri, tutup lagi. Diamkan selama 10 menit. Aduk dengan rata.",8000)
insert_data(database_makanan,"Sup tulang","MainCourse","main course",["1/2 kg tulang sapi","sayur","4 siung bawang putih,iris","4 bawang merah,iris","3 buah daun bawang,iris","2buah seledri,iris","1 buah tomat,potong","gula garam dan merica secukupnya"],"1. Bersihkan tulangan sapi. Rebus hingga air mendidih. Buang airnya cuci kembali. Lalu rebus hingga empuk, bisa menggunakan presto 2. Tumis bawang merah dan bawang putih. masukkan air dan tulangan sapi. Tunggu hingga mendidih lalu masukkan wortel dan kentang.3. Tambahkan irisan daun bawang, seledri, gula garam dan merica. Rebus selama 30 menit dengan api kecil. Koreksi rasa. Terakhir taburkan bawang goreng.",15000)
insert_data(database_makanan,"Jengkol Kalio","MainCourse","main course",[" 250 gram jengkol tua yang sudah direbus, pipihkan"," 700 ml santan cair","1 batang sereh memarkan","4 lembar daun salam","4 lembar daun jeruk sobek-sobek","garam, kaldu jamur, merica bubuk dan sedikit gula pasir/gula merah"],"1. Tumis bumbu halus sampai wangi, masukkan sereh, salam dan daun jeruk tumis lagi agak lama sampai bumbu benar-benar matang dan mengeluarkan minyak 2. Masukkan santan dan jengkol, didihkan. Bumbui garam, kaldu jamur, merica dan gula sesuai selera.3. Masak sampai bumbu meresap dan kuah santan menyusut. Jangan lupa cek rasa, angkat sajikan dengan nasi hangat.",7000)
insert_data(database_makanan,"Tumis Sawi Taunge","MainCourse","main course",["1 ikat sawi hijau","Wortel secukupnya", "Taoge secukupnya"],"1. Tumis bumbu iris sampai harum, masukkan wortel, masak sebentar 2. Kemudian masukkan sawi dan tauge, lalu tambahkan saus tiram, garam dan penyedap rasa.3. Masak sebentar, koreksi rasa.",6000)
insert_data(database_makanan,"Cumi pedas manis","MainCourse","main course",["1 kg cumi ukuran besar cuci bersih kemudian beri sedikit cuka dan garam, potong sesuai selera. Lalu cuci lagi sampai bersih","2 papan petai"],"1 Tumis bumbu halus sampai matang lalu masukkan cumi. aduk rata 2.Beri sedikit air (100 ml) kalau sudah mendidih masukkan semua bumbu.3.Masukkan saat kuah mulai sedikit surut dan mengental masukkan semua bumbu iris plus petai.4 Aduk-aduk biarkan sebentar lalu angkat.",10000)
insert_data(database_makanan,"Ayam panggang","MainCourse","main course",["1 ekor ayam kampung”,”1 lembar dauan kunyit","250 ml santan segar","air asam jawa secukupnya","air secukupnya","garam, gula dan kadlu bubuk"],"1 Panaskan minyak tumis semua bahan halus dan daun kunyit sampai wangi 2. Masukkan santan, garam, gula, kaldu bubuk, air dan air asam jawa secukupnya aduk rata.3. Masukkan ayam, ungkep ayam sampai empuk, sisahkan kuahnya 4. Bakar ayam di alat pemanggang, bolak balik sambil olesi sisa bumbu.5. Angkat dan siram kuah.",15000)
insert_data(database_makanan,"Ayam opor","MainCourse","main course",["1 ekor ayam ,potong 12 bagian","500 ml santan","1 ruas lengkuas","Gula secukupnya","Garam secukupnya"],"1. Rebus ayam untuk menghilangkan darah dan kotoran. Bisa juga dengan digoreng sebentar.2. Tumis bumbu halus sampai harum dan matang, masukkan ayam dan santan lalu masak sampai bumbu meresap. Taburi dengan gula, garam dan kaldu bubuk. Koreksi rasa.",13000) 
insert_data(database_makanan,"Telor balado","MainCourse","main course",["8 butir telur rebus","12 biji cabai merah","3 biji cabi rawit merah","6 butir bawang merah","2 butir bawang merah","2 batang serai geprek","2 buah tomat merah","garam","gula pasir","minyak goreng","1 blok terasi"],"1 Goreng telur hingga kuning keemasan. Angkat, lalu sisihkan.2. Haluskan (diulek atau diblender) cabai merah, cabai rawit merah, bawang merah, bawang putih, terasi bakar, dan tomat.3. Tumis serai hingga wangi, lalu masukkan bumbu halus, tumis hingga harum 4. Beri garam dan gula secukupnya.5. Masukkan telur, aduk sampai merata.",6000)

# Menyimpan database makanan ke dalam file JSON
save_to_json(database_makanan)
