insert_data(database_makanan, "Tongkol Suwir Pedas", "Olahan Tongkol dengan Sambal", "main course", ["2 lembar daun jeruk ", "1 buah jeruk nipis", "Garam", "Gula", "Kaldu bubuk", "Minyak goreng","3 siung bawang putih","5 buah cabai merah besar","4 siung bawang merah","10 buah cabe rawit merah"], "1. Rebus ikan tongkol sampai matang, angkat dan suwir 2. Haluskan seluruh bumbu halus dengan blender. 3.Tumis bumbu halus sampai harum", "4. Tambahkan daun jeruk, perasan jeruk nipis, air, garam, dan gula 5.Masukkan ikan yang telah disuwir, aduk hingga merata 5.Diamkan sejenak hingga bumbu terserap sempurna. 6. Angkat lalu sajikan di piring.", 20000)

insert_data(database_makanan, "Capcay Goreng", "Olahan sayuran dengan bumbu", "main course", ["Kol", "Sawi", "Wortel", "Brokoli", "Bakso", "Pakcoy", "Jamur","saos","kecap asin","saus tiram"], "1. Panaskan wajan kemudian tumis bawang putih dan cabai merah hingga harum. 2. Tuang telur dan orak arikkan telur.", "3.Kemudian tambahkan buncis dan jamur. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 10000)

insert_data(database_makanan, "Gado Gado", "Olahan sayuran, tempe dan tahu dengan bumbu kacang", "main course", ["mentimun", "kol", "tahu", "tempe", "labu siam", "kacang panjang", "tomat","kerupuk","emping", "kentang","buncis","taoge","telur"], "1. Aduk rata tempe dan tahu bersama bumbu perendam. Sisihkan. 2. Panaskan minyak, goreng tahu dan tempe hingga garing dan matang. Angkat dan tiriskan.", "3.Bumbu kacang: Panaskan 3 sdm minyak, tumis bumbu halus dan daun jeruk hingga harum. Masukkan kacang tanah dan Bango Kecap Manis, aduk rata. Tambahkan sisa semua bahan, aduk. Masak hingga matang. Angkat. Biarkan hingga tidak panas", "4.Tata kentang, tahu, tempe, daun selada, ketimun, taoge, dan kol di atas piring saji. Tuang bumbu kacang dan taburi bawang merah goreng. Sajikan dengan pelengkap 5.Angkat dan sajikan" ,  12000)

insert_data(database_makanan, "Martabak", "Olahan sayuran dan daging yang dibalut dengan kulit lumpia", "appetizer", ["kulit lumpia", "Bawang Putih", "daging ayam", "bawang putih", "1/4 sendok teh merica bubuk", "telur"], "1. campurkan 5 gram daun bawang, diiris halus 2 butir telur bebek, dikocok lepas 1/2 buah bawang bombay cincang halus 1/2 sendok teh garam 1/4 sendok teh merica bubuk 50 gram bahan tumisan daging. 2. Tuang telur dan orak arikkan telur.","3.Kemudian tambahkan buncis dan jamur. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 10000)

insert_data(database_makanan, "Kangkung Balacan", "Olahan kangkung dengan bumbu balacan", "diet Food", ["Kangkung", "Tomat", "2 Cabai Merah", "1 sdt terasi", "sedikit garam", "2 siung bawang putih", "gula secukupnya","2 buah cabai rawit","minyak goreng"], "1. Rebus kangkung, angkat dan tiriskan. 2. Tumis bumbu yang sudah ditumbuk sampai berbau harum dan matang, masukkan tomat sampai layu.", "3. Hidangkan rebusan kangkung dengan menyiram bumbu di atasnya. Siap sajikan. Tumis hingga setengah layu 4.Masukkan sedikit air kemudian diamkan hingga semua bumbu meresap sempurna 5.Angkat dan sajikan" , 7000)

insert_data(database_makanan, "Telur Sambal", "Olahan Telur dengan sambal pedas", "main course", ["4 buah telur ayam, rebus matang lalu goreng hingga berkulit", "2 siung bawang putih", "8 butir bawang merah", "2 buah cabai merah besar", "10 buah cabai rawit", "1 lembar daun jeruk, buang tulangnya", " 1 buah tomat iris", "1/2 sdt terasi matang", "gula, garam, kaldu bubuk secukupnya"], "1. Tumis bahan sambal bersama terasi dan daun jeruk hingga harum dan matang, beri air secukupnya", "2. Masukkan telur dan irisan tomat, bumbui dengan gula, garam dan kaldu bubuk, koreksi rasanya, masak hingga kuah asat", "3.Taburi daun bawang, siap disajikan.", 10000)

insert_data(database_makanan, "Sup Ayam Kentang", "Olahan Ayam dengan Sup Kentang yang fresh", "appetizer", ["200 gram kentang", "2 siung bawang putih", "100 gram wortel", "250 gram daging ayam", "1 tangkai seledri", "1 batang daun bawang"], "1. Tumis Bumbu yang telah di haluskan hingga tercium wangi nya 2. Tambahkan garam dan merica secukupnya 3.Tambahkan 1 Liter air 4. Jika sudah mendidih masukkan ayam dan sayuran 5. Aduk sampai merata 6. Tunggu sampai matang 7. Tiriskan dan ambil kuah secukupnya 8. Sajikan selagi masih hangat", 25500)

insert_data(database_makanan, "Tinutuan", "Olahan beras yang menjadi bubur dimasak dengan aneka umbi dan sayur", "appetizer", ["200 gram labu kuning, kukus", "100 gram labu kuning", "100 gram jagung manis", "150 gram beras", "2 liter air","1 sdm garam", "2 ikat daun kangkung", "2 ikat daun bayam", "3 tangkai daun kemangi", "100 gram ikan cakalang", "3 sdm sambal roa", "3 buah lemon"], "1. Kukus serta haluskan labu kuning 2. Potong kotak labu kuning 3. rebus jagung manis serta pipilkan 4. siangi 2 ikat daun kangkung serta daun bayam 5. Ambil daun kemangi dari tangkai nya 6. Potong-potong ikan cakalang 7. Dalam satu panci besar rebus berasserta air dan labu kuning yang sudah dikukus dan beri garam. Aduk sampai beras setengah matang 8. Masukkan jagung, ubi merah dan labu kuning. Aduk dan masak sampai matang 9.Saat bubur sudah matang, masukkan kangkung, bayam, dan daun kemangi 10. Sajikan dengan sambal roa dan suwiran ikan cakalang", 15000)

insert_data(database_makanan, "Salad Buah Mayonaise", "Olahan Salah buah dengan saos mayonaise", "appetizer", ["1 Buah pir", "1 Buah Sunkist", "1 Buah jeruk medan", "0.5 Buah bengkoang","150 gram Anggur merah" "100 gram Strawberry", "6 sdm Mayonaise", "4 sdm Susu Kental Manis", "Keju parut secukupnya"], "1. Cuci Bersih buah 2. Potong buah sesuai selera potongan 3. Campurkan semua buah ke dalam satu wadah 4. Beri mayonaise buah yang suah di campurkan 5. Berikan taburan keju parut dan aduk kembali sampai rata 6. Sajikan dengan porsi yang di inginkan", 17000)

insert_data(database_makanan, "Pancake Mangga", "Buah mangga yang di lapisi dengan kulit pancake", "dessert", ["125 gr tepung terigu" "1 butir telur ayam" "1/4 sdt garam" "275 ml susu cair" "Buah Mangga" "Whip Cream"], "1. kocok telur ayam terlebih dahulu 2. Campurkan tepung terigu, garam dan telur jadi satu 3.Tambahkan susu cair secara perlahan sambil diaduk-aduk 4. Saring adonan 5. Dadar di tempat penggoreng sampai adonan habis 6. Isi kulit pancake dengan whipping cream dan mangga, lipat seperti amplop 7. Simpan pancake di kulkas. Pancake mangga enak dimakan dalam kondisi dingin", 1900)

insert_data(database_makanan, "Taco Ikan", "Taco Ikan dengan selada dan kubis herbal", "diet food", ["Ikan Tuna","kulit lumpia","kubis","selada","Tarragon","jeruk nipis", "garam", "½ cangkir krim asam", "1 sdt jintan tanah1 jalapeno","2 sdm air jeruk nipis", "Perasan 1 buah jeruk nipis"], "1. Bersihkan Tuna dan Potong sesuai selera, 2. Campurkan bahan selada dan kubis serta beri garam 3. Tunggu 10 menit 4. Campurkan bahan untuk krim dan beri bumbu dengan garam 5. Goreng Ikan tuna dengan bumbu selada serta sudah di bungkus dengan kulit lumpia 6. Setelah itu sajikan di piring", 45000)

insert_data(database_makanan, "Steak Tempe", "Steak versi diet food dengan sayur dan kacang", "diet food", ["1/2 papan tempe", "2 sdm tepung gluten free", "1/2 sdt lada putih", "garam secukupnya", "minyak kelapa", "air secukupnya"], "1. Kukus tempe sampai matang. Kemudian haluskan. 2. Campur tempe dengan tepung, lada putih, dan garam. 3. Bentuk sesuai selera, masak dengan api kecil hingga matang. Angkat dan sisihkan. 4. Saus: tumis bawang putih sampai harum. Masukkan bawang bombay, aduk sampai layu. 5. Masukkan semua bahan lain kecuali garam. Masak sampai mendidih. 6. Matikan api, beri garam lalu aduk rata. 7. Tuang saus ke steak tempe.", 13000)

insert_data(database_makanan, "Sup kacang merah", "Sup dengan versi diet serta tambahan kacang merah yang lezat", "diet food", ['kentang', '2 butir telur', 'timun', 'tomat', 'selada', 'wortel', '150 ml air', '2 sdm fiber krim', '1 sdt garam', '1 sdm air lemon'], '1. Didihkan air, masukkan fiber creme lalu aduk rata. 2. Masukkan larutan maizena, aduk sampai mengental. 3. Beri himsalt dan air lemon, aduk rata. 4. Sajikan sayur dan telur dengan saus yang sudah jadi.', 6000)

insert_data(database_makanan, "Dimsum gulung sawi", "Dimsum dengan versi diet food di bungkus dengan sawi", 'diet food', ['500 gr paha ayam fillet', '100 gr udang', '2 putih telur', '2 siung bawang putih yang sudah dihaluskan', '4 sdm saus tiram non MSG', '1/2 sdt garam', '1 sdt kecap asin organik', '1 ujung sendok lada', 'sawi'], '1. Haluskan semua bahan kecuali sawi. 2. Gulung isian dengan sawi yang sudah direbus di air mendidih sebentar. 3. Kukus sampai matang.', 7000)

insert_data(database_makanan, "Mi Ayam Shirataki", "Mi ayam dengan versi diet food", "diet food", ['50 gr ayam giling', '1 sdm bawang putih halus', 'Garam', 'Lada', 'Kulit ayam', 'Lemak ayam', 'Mie shirataki sceukupnya', '2 sdt kecap asin', '1 sdm minyak ayam', '1/2 sdt merica bubuk'], '1. Masak semua bahan topping di teflon hingga kering dan keluar minyak nya. 2. blender hingga halus bahan yang ada di teflon. 3. Masak minyak ayam kulit dan lemak dimasak tanpa minyak hingga keluar minyaknya. 3. Rebus mi shirataki 4. angkat dan tiriskan 5. Beri kecap asin, minyak ayam, dan lada bubuk di mangkuk lalu aduk hingga rata. 6. Setelah di aduk sampai merata sajikan dengan tambahan topping', 12500)

insert_data(database_makanan, "Green Pasta", "Pasta yang cocok untuk yang sedang diet", ['Fettucine secukupnya', 'Brokoli', '1 buah tomat kecil', '1/4 paprika hijau', '3 siung bawang putih yang cincang halus', 'Lada hitam', '1 sdm minyak wijen', 'Garam himalaya', '2 buah telur ayam ambil bagian putih nya saja'], '1. Rebus fettuccine dan brokoli. Jika sudah matang tiriskan. Air bekas rebusan pasta disisakan sedikit.2. Panaskan penggorengan, masukkan minyak jagung, tumis bawang putih sebentar saja. 3. Masukkan tomat hijau dan paprika hijau. Tumis sebentar, masukkan air bekas rebusan pasta sedikit. 4. Masukkan fettuccine, brokoli, dan telur orak arik. 5. Tambahkan minyak wijen, garam himalaya, dan lada hitam sesuai selera. 6. Aduk sebentar kira-kira 3-5 menit', 18000)